###### Copyright Easton Potokar, 2020

name: Convert PDF to Images

on:
  push:
    branches:
      - 'main'
    paths:
      - 'DIPFall2025_Marino_David_Assignement1A.pdf'
      - '.README.md'
      - '.github/workflows/writeup_readme.yml'


jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ghostscript
        run: sudo apt-get update && sudo apt-get install -y ghostscript

      - name: Convert PDF with ImageMagick
        uses: jruipinto/ImageMagick-action@v1
        with:
          INPUT_COMMAND: magick -density 250 -trim -colorspace sRGB -alpha remove writeup.pdf -quality 85 output-%03d.jpg

    ## COMMIT THEM TO A ORPHAN BRANCH
    - name: Commit images to orphan branch
      run: |
        git checkout --orphan ${{env.ORPHAN_BRANCH}}
        touch .README.md
        mv .README.md .README.temp
        git rm -rf .
        git add *.jpg
        git config --local user.email "action@github.com"
        git config --local user.name "GithubActions"
        git commit -m "Updated writeup images" -a
    - name: Push images to orphan branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.ORPHAN_BRANCH }}
        force: true

    ## UPDATE README IN BRANCH IF IT NEEDS TO BE UPDATED
    - name: Update Readme
      id: main
      run: |
        echo $'\n' >> .README.temp
        for filename in *.jpg; do \
          echo '![image](https://github.com/'$GITHUB_REPOSITORY'/blob/${{env.ORPHAN_BRANCH}}/'$filename'?raw=true)' >> .README.temp;  \
        done
        git checkout ${{ github.ref }}
        rm README.md || (exit 0)
        mv .README.temp README.md
        OUTPUT=0
        git diff --exit-code README.md || OUTPUT=$?
        echo "::set-output name=OUTPUT::$OUTPUT"
    - name: Commit new README (if changed)
      if: steps.main.outputs.OUTPUT == 1
      run: |
        git add README.md
        git config --local user.email "action@github.com"
        git config --local user.name "GithubActions"
        git commit -m "Updated Readme" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
